<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260522114540 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_society (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(255) NOT NULL, user_id INT NOT NULL, society_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_55697FF8A76ED395 ON user_society (user_id)');
        $this->addSql('CREATE INDEX IDX_55697FF8E6389D24 ON user_society (society_id)');
        $this->addSql('ALTER TABLE user_society ADD CONSTRAINT FK_55697FF8A76ED395 FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_society ADD CONSTRAINT FK_55697FF8E6389D24 FOREIGN KEY (society_id) REFERENCES society (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE UNIQUE INDEX uniq_user_society ON user_society (user_id, society_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_society DROP CONSTRAINT FK_55697FF8A76ED395');
        $this->addSql('ALTER TABLE user_society DROP CONSTRAINT FK_55697FF8E6389D24');
        $this->addSql('DROP TABLE user_society');
    }
}
