<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260526195717 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE referential_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_a90838d88c6a6966e56f6020b29f1a4e_idx ON referential_audit (type)');
        $this->addSql('CREATE INDEX object_id_a90838d88c6a6966e56f6020b29f1a4e_idx ON referential_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_a90838d88c6a6966e56f6020b29f1a4e_idx ON referential_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_a90838d88c6a6966e56f6020b29f1a4e_idx ON referential_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_a90838d88c6a6966e56f6020b29f1a4e_idx ON referential_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_a90838d88c6a6966e56f6020b29f1a4e_idx ON referential_audit (created_at)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE referential_audit');
    }
}
