<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260511094150 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, active BOOLEAN NOT NULL, ordre INT NOT NULL, referential_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_64C19C175DD17F9 ON category (referential_id)');
        $this->addSql('CREATE TABLE measure_node (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, label VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, ordre INT NOT NULL, active BOOLEAN NOT NULL, applies_to_ee BOOLEAN DEFAULT NULL, applies_to_ei BOOLEAN DEFAULT NULL, category_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C2A6AEF112469DE2 ON measure_node (category_id)');
        $this->addSql('CREATE INDEX IDX_C2A6AEF1727ACA70 ON measure_node (parent_id)');
        $this->addSql('CREATE TABLE referential (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(50) NOT NULL, label VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, version VARCHAR(50) DEFAULT NULL, active BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON users (email)');
        $this->addSql('ALTER TABLE category ADD CONSTRAINT FK_64C19C175DD17F9 FOREIGN KEY (referential_id) REFERENCES referential (id)');
        $this->addSql('ALTER TABLE measure_node ADD CONSTRAINT FK_C2A6AEF112469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE measure_node ADD CONSTRAINT FK_C2A6AEF1727ACA70 FOREIGN KEY (parent_id) REFERENCES measure_node (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE category DROP CONSTRAINT FK_64C19C175DD17F9');
        $this->addSql('ALTER TABLE measure_node DROP CONSTRAINT FK_C2A6AEF112469DE2');
        $this->addSql('ALTER TABLE measure_node DROP CONSTRAINT FK_C2A6AEF1727ACA70');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE measure_node');
        $this->addSql('DROP TABLE referential');
        $this->addSql('DROP TABLE users');
    }
}
