<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260513134054 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE campaign (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, referential_id INT NOT NULL, society_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1F1512DD75DD17F9 ON campaign (referential_id)');
        $this->addSql('CREATE INDEX IDX_1F1512DDE6389D24 ON campaign (society_id)');
        $this->addSql('CREATE TABLE measure_review (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, proof_url VARCHAR(255) DEFAULT NULL, explanation TEXT DEFAULT NULL, not_applicable_reason TEXT DEFAULT NULL, campaign_id INT NOT NULL, measure_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_66554906F639F774 ON measure_review (campaign_id)');
        $this->addSql('CREATE INDEX IDX_665549065DA37D00 ON measure_review (measure_id)');
        $this->addSql('CREATE TABLE remediation_action (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, priority VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, due_date DATE DEFAULT NULL, measure_review_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C49F09095876E8D3 ON remediation_action (measure_review_id)');
        $this->addSql('CREATE TABLE society (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, active BOOLEAN NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D6461F2727ACA70 ON society (parent_id)');
        $this->addSql('ALTER TABLE campaign ADD CONSTRAINT FK_1F1512DD75DD17F9 FOREIGN KEY (referential_id) REFERENCES referential (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE campaign ADD CONSTRAINT FK_1F1512DDE6389D24 FOREIGN KEY (society_id) REFERENCES society (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE measure_review ADD CONSTRAINT FK_66554906F639F774 FOREIGN KEY (campaign_id) REFERENCES campaign (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE measure_review ADD CONSTRAINT FK_665549065DA37D00 FOREIGN KEY (measure_id) REFERENCES measure_node (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE remediation_action ADD CONSTRAINT FK_C49F09095876E8D3 FOREIGN KEY (measure_review_id) REFERENCES measure_review (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE society ADD CONSTRAINT FK_D6461F2727ACA70 FOREIGN KEY (parent_id) REFERENCES society (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE campaign DROP CONSTRAINT FK_1F1512DD75DD17F9');
        $this->addSql('ALTER TABLE campaign DROP CONSTRAINT FK_1F1512DDE6389D24');
        $this->addSql('ALTER TABLE measure_review DROP CONSTRAINT FK_66554906F639F774');
        $this->addSql('ALTER TABLE measure_review DROP CONSTRAINT FK_665549065DA37D00');
        $this->addSql('ALTER TABLE remediation_action DROP CONSTRAINT FK_C49F09095876E8D3');
        $this->addSql('ALTER TABLE society DROP CONSTRAINT FK_D6461F2727ACA70');
        $this->addSql('DROP TABLE campaign');
        $this->addSql('DROP TABLE measure_review');
        $this->addSql('DROP TABLE remediation_action');
        $this->addSql('DROP TABLE society');
    }
}
