<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260523121349 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE evidence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, original_filename VARCHAR(255) NOT NULL, stored_filename VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, file_size INT NOT NULL, description TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, measure_review_id INT NOT NULL, uploaded_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C6157105876E8D3 ON evidence (measure_review_id)');
        $this->addSql('CREATE INDEX IDX_C615710A2B28FE8 ON evidence (uploaded_by_id)');
        $this->addSql('ALTER TABLE evidence ADD CONSTRAINT FK_C6157105876E8D3 FOREIGN KEY (measure_review_id) REFERENCES measure_review (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE evidence ADD CONSTRAINT FK_C615710A2B28FE8 FOREIGN KEY (uploaded_by_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE evidence DROP CONSTRAINT FK_C6157105876E8D3');
        $this->addSql('ALTER TABLE evidence DROP CONSTRAINT FK_C615710A2B28FE8');
        $this->addSql('DROP TABLE evidence');
    }
}
