<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260526175745 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE society_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_d47ff551638b29376c1ee850c45dfb83_idx ON society_audit (type)');
        $this->addSql('CREATE INDEX object_id_d47ff551638b29376c1ee850c45dfb83_idx ON society_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_d47ff551638b29376c1ee850c45dfb83_idx ON society_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_d47ff551638b29376c1ee850c45dfb83_idx ON society_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_d47ff551638b29376c1ee850c45dfb83_idx ON society_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_d47ff551638b29376c1ee850c45dfb83_idx ON society_audit (created_at)');
        $this->addSql('CREATE TABLE users_audit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(10) NOT NULL, object_id VARCHAR(255) NOT NULL, discriminator VARCHAR(255) DEFAULT NULL, transaction_hash VARCHAR(40) DEFAULT NULL, diffs JSON DEFAULT NULL, blame_id VARCHAR(255) DEFAULT NULL, blame_user VARCHAR(255) DEFAULT NULL, blame_user_fqdn VARCHAR(255) DEFAULT NULL, blame_user_firewall VARCHAR(100) DEFAULT NULL, ip VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX type_5d977da36e91813e766863f2f579043a_idx ON users_audit (type)');
        $this->addSql('CREATE INDEX object_id_5d977da36e91813e766863f2f579043a_idx ON users_audit (object_id)');
        $this->addSql('CREATE INDEX discriminator_5d977da36e91813e766863f2f579043a_idx ON users_audit (discriminator)');
        $this->addSql('CREATE INDEX transaction_hash_5d977da36e91813e766863f2f579043a_idx ON users_audit (transaction_hash)');
        $this->addSql('CREATE INDEX blame_id_5d977da36e91813e766863f2f579043a_idx ON users_audit (blame_id)');
        $this->addSql('CREATE INDEX created_at_5d977da36e91813e766863f2f579043a_idx ON users_audit (created_at)');
        $this->addSql('CREATE UNIQUE INDEX uniq_campaign_measure_review ON measure_review (campaign_id, measure_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE society_audit');
        $this->addSql('DROP TABLE users_audit');
        $this->addSql('DROP INDEX uniq_campaign_measure_review');
    }
}
